"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Article } from "@/lib/article";
import { DwellTracker } from "./DwellTracker";

type ImageState = "loading" | "ready" | "none";
type Status = "streaming" | "done" | "blocked" | "error";

export function StreamingArticle({
  slug,
  title,
}: {
  slug: string;
  title: string;
}) {
  const [text, setText] = useState("");
  const [imageSrc, setImageSrc] = useState<string | null>(null);
  const [imageState, setImageState] = useState<ImageState>("loading");
  const [status, setStatus] = useState<Status>("streaming");
  const [notice, setNotice] = useState<{ title: string; body: string } | null>(
    null
  );

  // Buffer text deltas and flush once per animation frame so react-markdown
  // re-renders smoothly rather than on every token.
  const bufRef = useRef("");
  const rafRef = useRef<number | null>(null);

  useEffect(() => {
    const controller = new AbortController();

    const flush = () => {
      rafRef.current = null;
      setText(bufRef.current);
    };
    const scheduleFlush = () => {
      if (rafRef.current == null) rafRef.current = requestAnimationFrame(flush);
    };

    const handle = (evt: any) => {
      switch (evt?.type) {
        case "delta":
          bufRef.current += evt.text ?? "";
          scheduleFlush();
          break;
        case "image":
          setImageSrc(evt.src ?? null);
          setImageState(evt.src ? "ready" : "none");
          break;
        case "noimage":
          setImageState("none");
          break;
        case "cached":
          bufRef.current = evt.content ?? "";
          setText(bufRef.current);
          if (evt.image) {
            setImageSrc(evt.image);
            setImageState("ready");
          } else {
            setImageState("none");
          }
          break;
        case "blocked":
          setNotice({ title: evt.title, body: evt.body });
          setStatus("blocked");
          break;
        case "error":
          setNotice({
            title: "Couldn’t generate this article",
            body: evt.message || "Something went wrong. Please try again.",
          });
          setStatus("error");
          break;
        case "done":
          if (rafRef.current != null) cancelAnimationFrame(rafRef.current);
          setText(bufRef.current);
          setStatus((s) => (s === "streaming" ? "done" : s));
          setImageState((s) => (s === "loading" ? "none" : s));
          break;
      }
    };

    (async () => {
      try {
        const res = await fetch("/api/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ slug, title }),
          signal: controller.signal,
        });
        if (!res.ok || !res.body) throw new Error(`Request failed (${res.status}).`);

        const reader = res.body.getReader();
        const decoder = new TextDecoder();
        let buf = "";
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          buf += decoder.decode(value, { stream: true });
          let nl: number;
          while ((nl = buf.indexOf("\n")) >= 0) {
            const line = buf.slice(0, nl).trim();
            buf = buf.slice(nl + 1);
            if (line) handle(JSON.parse(line));
          }
        }
      } catch (err: any) {
        if (controller.signal.aborted) return;
        setNotice({
          title: "Couldn’t generate this article",
          body: err?.message || "The connection was interrupted. Please try again.",
        });
        setStatus("error");
      }
    })();

    return () => {
      controller.abort();
      if (rafRef.current != null) cancelAnimationFrame(rafRef.current);
    };
  }, [slug, title]);

  if (status === "blocked" || status === "error") {
    return (
      <main className="article">
        <nav className="topbar">
          <Link href="/" prefetch={false}>
            Create-Wiki
          </Link>
        </nav>
        <div className="notice">
          <h1 className="notice-title">{notice?.title}</h1>
          <p className="notice-body">{notice?.body}</p>
          <button className="notice-action" onClick={() => location.reload()}>
            Try again
          </button>
        </div>
      </main>
    );
  }

  const streaming = status === "streaming";

  return (
    <main className="article">
      {status === "done" && <DwellTracker slug={slug} />}
      <nav className="topbar">
        <Link href="/" prefetch={false}>
          Create-Wiki
        </Link>
      </nav>
      <article>
        <h1 className="article-title">{title}</h1>
        <p className="hatnote">
          This article was generated by AI and may be inaccurate or entirely
          fictional.
        </p>

        {imageState !== "none" && (
          <figure className="infobox">
            {imageState === "ready" && imageSrc ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img src={imageSrc} alt={title} className="infobox-img-in" />
            ) : (
              <div className="infobox-skeleton" aria-label="Generating image">
                <span className="infobox-spinner" aria-hidden />
              </div>
            )}
            <figcaption>
              {imageState === "ready" ? title : "Generating image…"}
            </figcaption>
          </figure>
        )}

        {text.length === 0 ? (
          <div className="body-skeleton" aria-label="Generating article">
            <span className="skel-line" style={{ width: "97%" }} />
            <span className="skel-line" style={{ width: "100%" }} />
            <span className="skel-line" style={{ width: "92%" }} />
            <span className="skel-line" style={{ width: "98%" }} />
            <span className="skel-line" style={{ width: "60%" }} />
          </div>
        ) : (
          <div className={streaming ? "is-streaming" : undefined}>
            <Article content={text} />
          </div>
        )}
      </article>
    </main>
  );
}
