import { ensureSchema, getTopPages, getRandomPages } from "@/lib/db";
import { SearchBox } from "./components/SearchBox";
import { SamplePrompts } from "./components/SamplePrompts";
import { ArticleCard } from "./components/ArticleCard";

export const dynamic = "force-dynamic";

export default async function Home() {
  await ensureSchema();

  const top = await getTopPages(6);
  const topSlugs = new Set(top.map((p) => p.slug));
  const pool = await getRandomPages(18);
  const random = pool.filter((p) => !topSlugs.has(p.slug)).slice(0, 6);

  const hasAny = top.length > 0 || random.length > 0;

  return (
    <main className="home">
      <header className="home-head">
        <h1 className="site-title">Create-Wiki</h1>
        <p className="site-sub">
          The AI-generated encyclopedia. Every article is written the moment you
          look for it.
        </p>
        <SearchBox />
        <SamplePrompts />
      </header>

      {hasAny ? (
        <div className="home-grid">
          {top.length > 0 && (
            <section className="panel">
              <h2 className="panel-title">Most read</h2>
              <div className="entry-list">
                {top.map((p) => (
                  <ArticleCard key={p.slug} page={p} />
                ))}
              </div>
            </section>
          )}

          {random.length > 0 && (
            <section className="panel">
              <h2 className="panel-title">Random articles</h2>
              <div className="entry-list">
                {random.map((p) => (
                  <ArticleCard key={p.slug} page={p} />
                ))}
              </div>
            </section>
          )}
        </div>
      ) : (
        <p className="empty">
          No articles yet. Search for anything above to create the first one.
        </p>
      )}

      <footer className="site-footer">
        All content is generated by AI and may be inaccurate or entirely fictional.
      </footer>
    </main>
  );
}
