import Link from "next/link";
import { ensureSchema, getPage, incrementView, type Page } from "@/lib/db";
import { Article } from "@/lib/article";
import { deslugify } from "@/lib/slug";
import { DwellTracker } from "@/app/components/DwellTracker";
import { StreamingArticle } from "@/app/components/StreamingArticle";

export const dynamic = "force-dynamic";
export const maxDuration = 60; // Opus + image generation can take a while

export default async function WikiPage({
  params,
  searchParams,
}: {
  params: { slug: string };
  searchParams: { t?: string };
}) {
  await ensureSchema();
  const slug = params.slug;

  // Cache hit: serve the finished article statically and count a reading.
  const existing = await getPage(slug);
  if (existing && existing.status === "generated" && existing.content) {
    await incrementView(slug);
    return <ArticleView page={existing} />;
  }

  // Miss: stream the generation live (text token-by-token + image placeholder).
  // All safeguards (daily cap, per-slug lock, concurrency) run in /api/generate.
  const title = searchParams.t?.trim() || existing?.title || deslugify(slug);
  return <StreamingArticle slug={slug} title={title} />;
}

function ArticleView({ page }: { page: Page }) {
  return (
    <main className="article">
      <DwellTracker slug={page.slug} />
      <nav className="topbar">
        <Link href="/" prefetch={false}>
          Create-Wiki
        </Link>
      </nav>
      <article>
        <h1 className="article-title">{page.title}</h1>
        <p className="hatnote">
          This article was generated by AI and may be inaccurate or entirely
          fictional.
        </p>
        {page.image_url && (
          <figure className="infobox">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={`/api/image/${page.slug}`} alt={page.title} />
            <figcaption>{page.title}</figcaption>
          </figure>
        )}
        <Article content={page.content!} />
      </article>
    </main>
  );
}
